# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Democracy in Austria
email: ""
description: ""
  
logo: "assets/images/2021-12-08-Nagarro-Oliver-Hoffmann-1-removebg-zoom-2-scaled-2.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: ""
bio: ""
author_image: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

defaults:
  -
    scope:
      path: "_posts" # empty string for all files
    values:
      layout: "post"
  -
    scope:
      path: "_posts/en"
    values:
      tags: English
